import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
	title: "Teman Sejati - Temani Momen Indah Pernikahanmu",
	description: "Generated by create next app",
	viewport: "width=device-width, initial-scale=1, viewport-fit=cover",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				{children}
				<Toaster />
			</body>
		</html>
	);
}
